import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  Film,
  Type,
  AlignLeft,
  Hash,
  Download,
  Home,
  FileDown,
  Timer,
} from 'lucide-react'
import FloatingPanel from '../components/ui/FloatingPanel'
import NeoButton from '../components/ui/NeoButton'
import CopyButton from '../components/ui/CopyButton'
import ErrorBanner from '../components/ui/ErrorBanner'
import { useGeneration } from '../context/GenerationContext'
import { assetUrl, parseHashtags } from '../lib/api'
import {
  buildPerformanceLines,
  formatPerformanceForCopy,
} from '../constants/phases'

function MediaPlaceholder({ aspect, label, icon: Icon }) {
  return (
    <div
      className={`neo-inset rounded-xl flex flex-col items-center justify-center gap-3 border border-white/[0.04] ${aspect}`}
    >
      <div className="h-14 w-14 rounded-xl neo-panel flex items-center justify-center">
        <Icon size={28} className="text-white/25" strokeWidth={1.25} />
      </div>
      <p className="text-xs text-white/30 text-center px-4 max-w-[200px]">{label}</p>
    </div>
  )
}

function downloadFile(url, filename) {
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.target = '_blank'
  a.rel = 'noopener'
  document.body.appendChild(a)
  a.click()
  a.remove()
}

export default function ResultPage() {
  const navigate = useNavigate()
  const { result, progress, jobId, clearJob, fetchAndStoreResult, error } =
    useGeneration()

  useEffect(() => {
    if (!jobId) {
      navigate('/', { replace: true })
      return
    }
    if (!result) {
      fetchAndStoreResult(jobId).catch(() => {
        navigate('/processing', { replace: true })
      })
    }
  }, [jobId, result, navigate, fetchAndStoreResult])

  if (!result) {
    return (
      <div className="max-w-lg mx-auto text-center py-20 text-white/40 text-sm">
        Loading results…
      </div>
    )
  }

  const videoUrl = assetUrl(result.video_path)
  const title = result.title || 'Untitled'
  const description = result.description || ''
  const hashtagList = parseHashtags(result.hashtags)
  const hashtagsCopy = hashtagList.map((t) => `#${t}`).join('\n')

  const metadataText = `${title}\n\n${description}\n\n${hashtagsCopy}`
  const perfSource = result.phase_timings?.length ? result : progress
  const performanceLines = buildPerformanceLines(perfSource)
  const performanceCopyText = formatPerformanceForCopy(perfSource)

  return (
    <div className="space-y-8 md:space-y-10">
      <motion.header
        className="text-center md:text-left"
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-white/30 mb-2">
          Export Dashboard
        </p>
        <h1 className="text-3xl md:text-4xl font-semibold tracking-tight text-white text-glow">
          Your Short Is Ready
        </h1>
        <p className="mt-2 text-white/40 text-sm max-w-xl">
          Generated by the AutoShorts pipeline
        </p>
      </motion.header>

      {error && <ErrorBanner title={error.title} message={error.message} />}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-5 md:gap-6">
        <FloatingPanel title="Video Preview" icon={Film} delay={0.05} span="full">
          {videoUrl ? (
            <video
              src={videoUrl}
              controls
              className="aspect-[9/16] max-h-[480px] w-full max-w-[280px] mx-auto rounded-xl neo-inset bg-black"
              playsInline
            />
          ) : (
            <MediaPlaceholder
              aspect="aspect-[9/16] max-h-[480px] w-full max-w-[280px] mx-auto"
              label="Video not available"
              icon={Film}
            />
          )}
        </FloatingPanel>

        <FloatingPanel title="Title" icon={Type} delay={0.1}>
          <div className="flex items-start justify-between gap-3">
            <p className="text-lg font-semibold text-white leading-snug flex-1">{title}</p>
            <CopyButton text={title} label="Copy" />
          </div>
        </FloatingPanel>

        <FloatingPanel title="Description" icon={AlignLeft} delay={0.15} span="2">
          <div className="flex flex-col gap-3">
            <p className="text-sm text-white/50 leading-relaxed whitespace-pre-wrap">
              {description}
            </p>
            <CopyButton text={description} label="Copy description" />
          </div>
        </FloatingPanel>

        <FloatingPanel title="Hashtags" icon={Hash} delay={0.2}>
          <div className="space-y-3">
            <div className="flex flex-wrap gap-2">
              {hashtagList.map((tag) => (
                <span
                  key={tag}
                  className="text-xs px-3 py-1.5 rounded-full neo-inset text-white/50 border border-white/[0.04]"
                >
                  #{tag}
                </span>
              ))}
            </div>
            <CopyButton text={hashtagsCopy} label="Copy hashtags" />
          </div>
        </FloatingPanel>

        {performanceLines.length > 0 && (
          <FloatingPanel title="Performance" icon={Timer} delay={0.25} span="full">
            <div className="space-y-3">
              <div className="font-mono text-sm text-white/65 space-y-1">
                {performanceLines.map((line) => (
                  <p
                    key={line}
                    className={
                      line.startsWith('TOTAL:')
                        ? 'text-emerald-400/90 pt-2 border-t border-white/10'
                        : ''
                    }
                  >
                    {line}
                  </p>
                ))}
              </div>
              <CopyButton text={performanceCopyText} label="Copy timings" />
              {jobId && (
                <p className="text-xs text-white/30">
                  Also saved as{' '}
                  <span className="text-white/45">jobs/{jobId}/performance.txt</span>{' '}
                  (if this run used the latest API).
                </p>
              )}
            </div>
          </FloatingPanel>
        )}

        <FloatingPanel title="Downloads" icon={Download} delay={0.3} span="full">
          <div className="flex flex-col sm:flex-row flex-wrap gap-3">
            <NeoButton
              variant="secondary"
              icon={FileDown}
              className="flex-1 min-w-[160px]"
              disabled={!videoUrl}
              onClick={() => videoUrl && downloadFile(videoUrl, 'output.mp4')}
            >
              Download Video
            </NeoButton>
            <NeoButton
              variant="secondary"
              icon={Download}
              className="flex-1 min-w-[160px]"
              onClick={() => {
                const blob = new Blob([metadataText], { type: 'text/plain' })
                const url = URL.createObjectURL(blob)
                downloadFile(url, 'metadata.txt')
                URL.revokeObjectURL(url)
              }}
            >
              Download Metadata
            </NeoButton>
          </div>
        </FloatingPanel>
      </div>

      <motion.div
        className="flex justify-center pt-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
      >
        <NeoButton
          variant="ghost"
          icon={Home}
          onClick={() => {
            clearJob()
            navigate('/')
          }}
        >
          Return Home
        </NeoButton>
      </motion.div>
    </div>
  )
}
